# Generated by Django 4.0.7 on 2023-11-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_registration_registrationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='image',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
